In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
fake = pd.read_csv("/mnt/d/01_Projects/NLP/AI CRM Brain/AI-CRM-Brain/test_deals.csv")
fake.head()

,Deal_ID,Deal_Name,Amount,Expected_Revenue,Probability,Stage,Closing_Date,Account_Name,Contact_Name,Owner_Name
0,7396871000000612198,King,60000,0,60,Id. Decision Makers,2026-05-08,King (Sample),Kris Marrier (Sample),Tamer Elkot
1,7396871000000612197,Truhlar And Truhlar Attys,45000,0,20,Needs Analysis,2026-05-06,Truhlar And Truhlar (Sample),Sage Wieser (Sample),Tamer Elkot
2,7396871000000612196,Commercial Press,45000,0,0,Closed Lost,2026-05-07,Commercial Press (Sample),Leota Dilliard (Sample),Tamer Elkot
3,7396871000000612195,Morlong Associates,35000,0,100,Closed Won,2026-05-08,Morlong Associates (Sample),Mitsue Tollner (Sample),Tamer Elkot
4,7396871000000612194,Chapman,70000,0,90,Negotiation/Review,2026-05-06,Chapman (Sample),Simon Morasca (Sample),Tamer Elkot

In [3]:
fake.columns

Index(['Deal_ID', 'Deal_Name', 'Amount', 'Expected_Revenue', 'Probability',
       'Stage', 'Closing_Date', 'Account_Name', 'Contact_Name', 'Owner_Name'],
      dtype='object')

In [4]:
maven_df = pd.read_csv("/mnt/d/01_Projects/NLP/AI CRM Brain/AI-CRM-Brain/data/raw data/sales_pipeline.csv")
maven_df.head()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,10/20/2016,3/1/2017,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,10/25/2016,3/11/2017,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,10/25/2016,3/7/2017,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,10/25/2016,3/9/2017,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,10/25/2016,3/2/2017,517.0

In [5]:
columns_to_keep = [
    'opportunity_id', 'sales_agent', 'account', 
    'deal_stage', 'close_value', 'close_date'
]

df = maven_df[columns_to_keep]
df.head()

  opportunity_id      sales_agent  account deal_stage  close_value close_date
0       1C1I7A6R      Moses Frase  Cancity        Won       1054.0   3/1/2017
1       Z063OYW0  Darcel Schlecht    Isdom        Won       4514.0  3/11/2017
2       EC4QE1BX  Darcel Schlecht  Cancity        Won         50.0   3/7/2017
3       MV1LWRNH      Moses Frase  Codehow        Won        588.0   3/9/2017
4       PE84CX4O        Zane Levy   Hatfan        Won        517.0   3/2/2017

In [6]:
df = df.rename(columns={
    'opportunity_id': 'Deal_ID',
    'sales_agent': 'Owner_Name',
    'account': 'Account_Name',
    'deal_stage': 'Stage',
    'close_value': 'Amount',
    'close_date': 'Closing_Date'
})

In [7]:
df.head()

    Deal_ID       Owner_Name Account_Name Stage  Amount Closing_Date
0  1C1I7A6R      Moses Frase      Cancity   Won  1054.0     3/1/2017
1  Z063OYW0  Darcel Schlecht        Isdom   Won  4514.0    3/11/2017
2  EC4QE1BX  Darcel Schlecht      Cancity   Won    50.0     3/7/2017
3  MV1LWRNH      Moses Frase      Codehow   Won   588.0     3/9/2017
4  PE84CX4O        Zane Levy       Hatfan   Won   517.0     3/2/2017

In [8]:
df.describe()

             Amount
count   6711.000000
mean    1490.915512
std     2320.670773
min        0.000000
25%        0.000000
50%      472.000000
75%     3225.000000
max    30288.000000

In [9]:
df.columns

Index(['Deal_ID', 'Owner_Name', 'Account_Name', 'Stage', 'Amount',
       'Closing_Date'],
      dtype='object')

In [10]:
df.shape

(8800, 6)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Deal_ID       8800 non-null   object
 1   Owner_Name    8800 non-null   object
 2   Account_Name  7375 non-null   object
 3   Stage         8800 non-null   object
 4   Amount        6711 non-null   float64
 5   Closing_Date  6711 non-null   object
dtypes: float64(1), object(5)
memory usage: 412.6+ KB