In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sales = pd.read_csv("/mnt/d/01_Projects/NLP/AI CRM Brain/AI-CRM-Brain/data/preprocessed/WA_Fn-UseC_-Sales-Win-Loss.csv")
sales.head()

,Opportunity Number,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
0,1641984,Exterior Accessories,Car Accessories,Northwest,Fields Sales,76,Won,13,104,101,0,5,5,0,Unknown,0.69636,0.113985,0.154215,1
1,1658010,Exterior Accessories,Car Accessories,Pacific,Reseller,63,Loss,2,163,163,0,3,5,0,Unknown,0.00000,1.000000,0.000000,1
2,1674737,Motorcycle Parts,Performance & Non-auto,Pacific,Reseller,24,Won,7,82,82,7750,1,1,0,Unknown,1.00000,0.000000,0.000000,1
3,1675224,Shelters & RV,Performance & Non-auto,Midwest,Reseller,16,Loss,5,124,124,0,1,1,0,Known,1.00000,0.000000,0.000000,1
4,1689785,Exterior Accessories,Car Accessories,Pacific,Reseller,69,Loss,11,91,13,69756,1,1,0,Unknown,0.00000,0.141125,0.000000,4

In [3]:
sales["Opportunity Result"].value_counts()

Opportunity Result
Loss    60398
Won     17627
Name: count, dtype: int64

In [4]:
fake = pd.read_csv("/mnt/d/01_Projects/NLP/AI CRM Brain/AI-CRM-Brain/test_deals.csv")
fake.head()

,Deal_ID,Deal_Name,Amount,Expected_Revenue,Probability,Stage,Closing_Date,Account_Name,Contact_Name,Owner_Name
0,7396871000000719033,cairo deal,80000,32000,40,Value Proposition,2026-08-12,SEG,Mohamed Elkot,Tamer Elkot
1,7396871000000719002,Mansura,10000,5000,50,Closed Won,2026-06-13,Feltz Printing Service (Sample),Capla Paprocki (Sample),Tamer Elkot
2,7396871000000612198,King,60000,0,60,Id. Decision Makers,2026-05-08,King (Sample),Kris Marrier (Sample),Tamer Elkot
3,7396871000000612197,Truhlar And Truhlar Attys,45000,0,20,Needs Analysis,2026-05-06,Truhlar And Truhlar (Sample),Sage Wieser (Sample),Tamer Elkot
4,7396871000000612196,Commercial Press,45000,0,0,Closed Lost,2026-05-07,Commercial Press (Sample),Leota Dilliard (Sample),Tamer Elkot

In [5]:
fake.columns

Index(['Deal_ID', 'Deal_Name', 'Amount', 'Expected_Revenue', 'Probability',
       'Stage', 'Closing_Date', 'Account_Name', 'Contact_Name', 'Owner_Name'],
      dtype='object')

In [6]:
maven_df = pd.read_csv("/mnt/d/01_Projects/NLP/AI CRM Brain/AI-CRM-Brain/data/raw data/sales_pipeline.csv")
maven_df.head()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,10/20/2016,3/1/2017,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,10/25/2016,3/11/2017,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,10/25/2016,3/7/2017,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,10/25/2016,3/9/2017,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,10/25/2016,3/2/2017,517.0

In [7]:
columns_to_keep = [
    'opportunity_id', 'sales_agent', 'account', 
    'deal_stage', 'close_value', 'close_date'
]

df = maven_df[columns_to_keep]
df.head()

  opportunity_id      sales_agent  account deal_stage  close_value close_date
0       1C1I7A6R      Moses Frase  Cancity        Won       1054.0   3/1/2017
1       Z063OYW0  Darcel Schlecht    Isdom        Won       4514.0  3/11/2017
2       EC4QE1BX  Darcel Schlecht  Cancity        Won         50.0   3/7/2017
3       MV1LWRNH      Moses Frase  Codehow        Won        588.0   3/9/2017
4       PE84CX4O        Zane Levy   Hatfan        Won        517.0   3/2/2017

In [8]:
df = df.rename(columns={
    'opportunity_id': 'Deal_ID',
    'sales_agent': 'Owner_Name',
    'account': 'Account_Name',
    'deal_stage': 'Stage',
    'close_value': 'Amount',
    'close_date': 'Closing_Date'
})

In [9]:
df.head()

    Deal_ID       Owner_Name Account_Name Stage  Amount Closing_Date
0  1C1I7A6R      Moses Frase      Cancity   Won  1054.0     3/1/2017
1  Z063OYW0  Darcel Schlecht        Isdom   Won  4514.0    3/11/2017
2  EC4QE1BX  Darcel Schlecht      Cancity   Won    50.0     3/7/2017
3  MV1LWRNH      Moses Frase      Codehow   Won   588.0     3/9/2017
4  PE84CX4O        Zane Levy       Hatfan   Won   517.0     3/2/2017

In [10]:
df["Stage"].value_counts()

Stage
Won            4238
Lost           2473
Engaging       1589
Prospecting     500
Name: count, dtype: int64

In [11]:
df.describe()

             Amount
count   6711.000000
mean    1490.915512
std     2320.670773
min        0.000000
25%        0.000000
50%      472.000000
75%     3225.000000
max    30288.000000

In [12]:
df.columns

Index(['Deal_ID', 'Owner_Name', 'Account_Name', 'Stage', 'Amount',
       'Closing_Date'],
      dtype='object')

In [13]:
df.shape

(8800, 6)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Deal_ID       8800 non-null   object
 1   Owner_Name    8800 non-null   object
 2   Account_Name  7375 non-null   object
 3   Stage         8800 non-null   object
 4   Amount        6711 non-null   float64
 5   Closing_Date  6711 non-null   object
dtypes: float64(1), object(5)
memory usage: 412.6+ KB